"""Add Adzuna job fetching preferences to AgentConfig

Revision ID: 2c5e6f9c180
Revises: 3f275de75860
Create Date: 2026-02-02 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5e6f9c180'
down_revision = '3f275de75860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adzuna_location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('adzuna_max_jobs', sa.Integer(), nullable=True, server_default='20'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.drop_column('adzuna_max_jobs')
        batch_op.drop_column('adzuna_location')

    # ### end Alembic commands ###