"""Add user preference learning columns

Revision ID: 3f275de75860
Revises: 
Create Date: 2026-02-02 12:56:53.854171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f275de75860'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preference_embedding', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('preference_updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_job_matches_resume_id'), ['resume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_job_matches_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_job_matches_resume_id', 'resumes', ['resume_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_job_matches_resume_id', type_='foreignkey')
        batch_op.drop_constraint('fk_job_matches_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_job_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_matches_resume_id'))
        batch_op.alter_column('resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.drop_column('preference_updated_at')
        batch_op.drop_column('preference_embedding')

    # ### end Alembic commands ###
